# Project Name
TARGET = UiSystemDemo

# Sources
CPP_SOURCES = UiSystemDemo.cpp

# Library Locations
LIBDAISY_DIR = ../../libdaisy

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
